### ISSUE TITLE
pod?

### ISSUE THREAD

**Issue by vitalrum** [ErAbhishekChandani/ACFloatingTextfield#1]
how to use it with pod?

**Comment by ErAbhishekChandani** [comment]
@Rumyancev 
Right now we are not supporting the cocoapods but we will add cocoapods support soon meanwhile you can use manual dragging classes files for now.

Thank You

**Comment by vitalrum** [comment]
thank you

**Comment by ErAbhishekChandani** [comment]
@vitalrum Pods integrated , you can install through following command...
pod "ACFloatingTextfield"
