### ISSUE TITLE
Ugly animation when resign first responder

### ISSUE THREAD

**Issue by gianfilippocisternino** [ErAbhishekChandani/ACFloatingTextfield#25]
When a text field resign first responder and the focus passes on another text field, it shows an horrible animation.
I attached the video of that issue.

[ACFloatingTextfield.zip](https://github.com/ErAbhishekChandani/ACFloatingTextfield/files/1077790/ACFloatingTextfield.zip)

I've tried to fix it, but i didn't find any fix. :(

**Comment by ErAbhishekChandani** [comment]
Hi,

        Thanks for bringing this issue upfront. Can you help me to reproduce this issue?
I need some information from your side.
1) In Which version you are facing this issue. (Obj-c or Swfit)
2) Did you check this issue in iPhone device or simulator? 
3) Which version of pod did you install?

Looking forward to your response Thanks.
