### ISSUE TITLE
Programatically hide error messages?

### ISSUE THREAD

**Issue by docash59** [ErAbhishekChandani/ACFloatingTextfield#27]
I love this library!
However, is there a way to dismiss the error message programmatically after using ``showError:``?

**Comment by ErAbhishekChandani** [comment]
currently textfield only dismiss the error when its clicked again or text is edited you can lavel new feature request for this So that I can address the requirement thanks.

**Comment by ErAbhishekChandani** [comment]
Resolved in pod v 1.5
