### ISSUE TITLE
POD not found

### ISSUE THREAD

**Issue by tomgekeerd** [ErAbhishekChandani/ACFloatingTextfield#3]
When I want to install this via Cocoapods I get the error:

[!] Unable to find a specification for `ACFloatingTextfield`

Probably meaning the pod can't be found. When looking for it on cocoapods.org I see no typos are made, so there must some issue with how you guys handle the pods I guess...

**Comment by ErAbhishekChandani** [comment]
Hi ,

         Please try to install through following pod command.

 pod “ACFloatingTextfield-Objc” , :git => 'https://github.com/ErAbhishekChandani/ACFloatingTextfield.git'

--
Thanks for bringing this problem , please close the issue if solved.
