### ISSUE TITLE
Placeholder text Cuts 

### ISSUE THREAD

**Issue by navjotcheema** [ErAbhishekChandani/ACFloatingTextfield#30]
when we use place holder text with Alphabet G:- Like Height , The below part of the Placeholder text cuts.
Attached is the screenshot
![screen shot 2017-09-11 at 12 45 31 am](https://user-images.githubusercontent.com/4949505/30252028-dd9bc09a-9688-11e7-9179-b490e5dde376.png)

**Comment by ErAbhishekChandani** [comment]
Thanks for reporting the issue, This will be resolved shortly. Thanks

**Comment by vijayender1991** [comment]
Please resolve this issue asap

**Comment by ErAbhishekChandani** [comment]
Resolved
