### ISSUE TITLE
animation is strange. xcode 9 ios 11

### ISSUE THREAD

**Issue by Levofloxacin** [ErAbhishekChandani/ACFloatingTextfield#33]
ACFloatingTextfield animation created by code is very strange.
ACFloatingTextfield created by Storyboard is no problem.

https://im3.ezgif.com/tmp/ezgif-3-cd780743a6.gif

**Comment by huynguyen1991** [comment]
same issues :((

**Comment by ErAbhishekChandani** [comment]
which version of pod you are using ? where you getting issues in objc or swift?

**Comment by Levofloxacin** [comment]
The latest version of yesterday. Used objc.

**Comment by huynguyen1991** [comment]
I am use version 1.5 , objc . error 
![simulator screen shot - iphone 6s - 2017-09-25 at 11 41 24](https://user-images.githubusercontent.com/22832543/30792671-88e255e6-a1e6-11e7-85ba-7704951c3039.png)

**Comment by huynguyen1991** [comment]
I am use version 1.5 . used objc 
Error frame
<img width="334" alt="screen shot 2017-09-25 at 11 42 42 am" src="https://user-images.githubusercontent.com/22832543/30792694-bb645dca-a1e6-11e7-8926-ee0d125c3b8e.png">

**Comment by Levofloxacin** [comment]
Error frame and animation is strange

**Comment by Levofloxacin** [comment]
![Uploading Unknown.gif…]()

**Comment by mrhaxic** [comment]
@Levofloxacin It fixed with the latest branch.

**Comment by dpksingh21** [comment]
in ios 11 text Field placeholder is not float when we start writing , after completing it floats.

**Comment by mrhaxic** [comment]
@dpksingh21  I tried the latest branch and it is working fine.

**Comment by ErAbhishekChandani** [comment]
Please use latest pod version 1.5 or fresh checkout from master branch If you still facing issues please let me know also let me know in which you getting issues (objc or swift) Thanks

**Comment by dpksingh21** [comment]
Issue resolved thank you @ErAbhishekChandani  @Levofloxacin  @mrhaxic
