### ISSUE TITLE
animation issue

### ISSUE THREAD

**Issue by Levofloxacin** [ErAbhishekChandani/ACFloatingTextfield#34]
https://im3.ezgif.com/tmp/ezgif-3-cd780743a6.gif

 xcode9
 ios11
 ACFloatingTextfield version 1.5 
 objc.

[ACFloatingTextfield-master-2.zip](https://github.com/ErAbhishekChandani/ACFloatingTextfield/files/1328474/ACFloatingTextfield-master-2.zip)

**Comment by ErAbhishekChandani** [comment]
This issue is resolved in latest version 1.6 please check and reopen if you still face the issue thanks.
