### ISSUE TITLE
lineColor's color can't changeable at first initialization

### ISSUE THREAD

**Issue by goktugaral** [ErAbhishekChandani/ACFloatingTextfield#37]
Hi,
I didn't have this situation while working on xCode 8 and iOS 10 devices. But its strangely occurs on xCode 9.
Could you look at it please?

I had to change the line;
```
/// Change Bottom Line Color.
- //@IBInspectable open var lineColor : UIColor = UIColor.black
+ @IBInspectable open var lineColor : UIColor?
```

**Comment by ErAbhishekChandani** [comment]
I think its resolved please check and open issue if you still facing thanks.
