### ISSUE TITLE
Not working on iOS11 

### ISSUE THREAD

**Issue by Fouda** [ErAbhishekChandani/ACFloatingTextfield#39]
still showing the text and not the "labelPlaceholder" when the textfield becomes firstRespond on the first time.

**Comment by ErAbhishekChandani** [comment]
please let me know in which you getting issue? objective c or swift are you using the version 1.5?

**Comment by Fouda** [comment]
in the initialization method you need to add 
` /// Placeholder Label Configuration.

    if (![self.text isEqualToString:@""]) {
        [self floatTheLabel];
    } else {
        self.text = @"";
    }`
in order to make it work ;)
