### ISSUE TITLE
use init ACFloatingTextfield don`t  set frame buttomLine is  not Normal work

### ISSUE THREAD

**Issue by zhuamaodeyu** [ErAbhishekChandani/ACFloatingTextfield#40]
this is my code , the buttomLine and line Color  not normal work 
        _pwdTextField = [[ACFloatingTextField alloc]init];
        [_pwdTextField setPlaceholder:@"密码"];
        _pwdTextField.tintColor = [UIColor colorWithRed:0.979  green:0.326  blue:0.380 alpha:1];
        [_pwdTextField setBackgroundColor:[UIColor whiteColor]];
        _pwdTextField.secureTextEntry = YES;
        _pwdTextField.selectedLineColor = [UIColor colorWithHexString:@"#999999"];
        _pwdTextField.selectedPlaceHolderColor = [UIColor colorWithHexString:@"#CCCCCC"];
        _pwdTextField.placeHolderColor = [UIColor colorWithHexString:@"#CCCCCC"];
        _pwdTextField.lineColor = [UIColor colorWithHexString:@"#E5E5E5"];
    }

the buttomLine frame  Y is 0 , is not self height - 1, and i set LineColor but is not use , you don`t code  setLineColor , init ButtomLine is init function, so ,i don`t know _lineColor is block color,you can reset `setLineColor` function. the is last version

**Comment by ErAbhishekChandani** [comment]
You should add constraint in your textfield or give to frame, then check it with latest version it may be addressed open again if you still facing issue thanks
