### ISSUE TITLE
Placeholder Missing for Non Visible Cells of TableViewController

### ISSUE THREAD

**Issue by YahyaBagia** [ErAbhishekChandani/ACFloatingTextfield#41]
I have a UITableViewController with Static Cells. These cells contain ACFloatingTextFields. I am configuring these text fields on viewDidLoad as :
`textField.selectedLineColor = [self getThemeColor];`
`textField.lineColor = [self getThemeColor];`
`textField.text = @"";`

The problem is that the visible cells (text fields) of UITableViewControllers display Placeholder. Non-Visible cells do not display placeholder. (Look for the attached GIFs.)

Am I missing something specific to UITableViewController? Please guide me.

I came across this issue but it looks different than my situation : #2  

I am using Objective-C version.

![issue_image_1](https://user-images.githubusercontent.com/25579208/32090203-e300ba20-bb0b-11e7-87d4-51deedb2499f.gif)
![issue_image_2](https://user-images.githubusercontent.com/25579208/32090211-edbae030-bb0b-11e7-84d1-5f4c1e04fa0d.gif)

**Comment by YahyaBagia** [comment]
Another problem related to Placeholder. An ACFloatingTextField is placed in Header of UITableViewController (with Dynamic Cells). It's visibility is toggled by Search Button in Navigation Bar. This textfield also loses placeholder once it gets focused. (Look for the attached GIF)
![giphy](https://user-images.githubusercontent.com/25579208/32101457-ec9daabe-bb35-11e7-9b4c-cdba20ddec22.gif)

**Comment by ErAbhishekChandani** [comment]
This issue has been resolved in v1.6 please check and reopen if still facing the issue thanks.

**Comment by YahyaBagia** [comment]
Seems resolved.. Thanks man..

**Comment by ErAbhishekChandani** [comment]
thanks for letting me know👍
