### ISSUE TITLE
Bug showing error

### ISSUE THREAD

**Issue by fricred** [ErAbhishekChandani/ACFloatingTextfield#45]
showErrorWithText is not hidding the placeholder 
![image](https://user-images.githubusercontent.com/5496992/32531138-29b83468-c410-11e7-8275-77bf2c2ceda9.png)

**Comment by ErAbhishekChandani** [comment]
showErrorWithText is not hiding the placeholder
this method shows the error, does not hide placeholder? do you want to hide the error ? then please use the hideError() method or checkout the latest version 1.7 , in which many bugs has been fixed, Reopen the issue if you face any issue.
