### ISSUE TITLE
Place holder Issue

### ISSUE THREAD

**Issue by kishorehvk** [ErAbhishekChandani/ACFloatingTextfield#50]
When I open a new page , where i kept acfloatingtextfield with some value , placeholder is not coming. When i again open then only it is visible. can you kindly check this.

Thanks in advance

**Comment by anhmuonnoi** [comment]
![simulator screen shot - iphone 6s - 2017-12-27 at 09 48 06](https://user-images.githubusercontent.com/6723051/34369023-385cfb46-eaeb-11e7-9b86-9e178539f0a2.png)
![simulator screen shot - iphone 6s - 2017-12-27 at 09 48 11](https://user-images.githubusercontent.com/6723051/34369024-388c2c04-eaeb-11e7-9dd3-4a7b651f9871.png)

**Comment by anhmuonnoi** [comment]
![simulator screen shot - iphone 6s - 2017-12-27 at 09 48 11](https://user-images.githubusercontent.com/6723051/34369045-60cad5bc-eaeb-11e7-9ba4-f6b57dbb4b61.png)

**Comment by ErAbhishekChandani** [comment]
Please re-open if this is still a problem!
