### ISSUE TITLE
Obj c file getting lot of warnings

### ISSUE THREAD

**Issue by Lyankar** [ErAbhishekChandani/ACFloatingTextfield#55]
@ErAbhishekChandani ErAbhishekChandani Obj c file is completely out dated. Can you please update the file. It's getting lot of warnings around 20+.

**Comment by ErAbhishekChandani** [comment]
Ok will fix ASAP Thanks

**Comment by Lyankar** [comment]
Thank you very much...

**Comment by ErAbhishekChandani** [comment]
I am not getting any warning in latest xcode. Please re-open if this is still a problem also attach the screenshots and info regarding xcode version you are using.
