### ISSUE TITLE
_placeholderLabel. issue 

### ISSUE THREAD

**Issue by UmerAfzal1** [ErAbhishekChandani/ACFloatingTextfield#59]
[<ACFloatingTextField 0x7fbec4e057d0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _placeholderLabel.'

**Comment by ErAbhishekChandani** [comment]
When and where you getting this issue, Please provide some more details 
Xcode verison
Langauge (Objective C or swift)
Steps to reproduce issue.
