### ISSUE TITLE
Library is not working in Xcode 11

### ISSUE THREAD

**Issue by AnkuriOSDevs** [ErAbhishekChandani/ACFloatingTextfield#68]
UITextField's _placeholderLabel ivar is prohibited. This is an application bug'
![Screenshot 2019-09-23 at 3 59 14 PM](https://user-images.githubusercontent.com/17780917/65418935-323f4000-de1b-11e9-9485-34c8dd4ad932.png)

**Comment by Axtel209** [comment]
I submitted a PR with the fix for it, just waiting to be approved. If you need a fix supper fast you can check out the changes in the PR and do them locally, until it's merged.

**Comment by ErAbhishekChandani** [comment]
Fixed check in latest pod version 1.8

**Comment by AnkuriOSDevs** [comment]
Thank you ErAbhishekChandani
Thank a lot
