### ISSUE TITLE
Issue in ios 13

### ISSUE THREAD

**Issue by ankit199102** [ErAbhishekChandani/ACFloatingTextfield#70]
Hi,

I got some error related to attribute string to resolve that you need remove line no 159 in m file.

_Originally posted by @ankit199102 in https://github.com/ErAbhishekChandani/ACFloatingTextfield/issues/69#issuecomment-536320055_

**Comment by ErAbhishekChandani** [comment]
will check this thanks

**Comment by ErAbhishekChandani** [comment]
Resolved Please check in latest release objective c - 1.9 and swift - 1.9
