### ISSUE TITLE
iOS 13 placeHolder 

### ISSUE THREAD

**Issue by niloufarMakhzani** [ErAbhishekChandani/ACFloatingTextfield#72]
My app crashes with this issue:
"  Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug' "
Which is related to this library, as I searched is in iOS 13. would you please fix this.

**Comment by vyskocil** [comment]
This seems to be the same issue as https://github.com/ErAbhishekChandani/ACFloatingTextfield/issues/71

**Comment by chitranjank** [comment]
pleases solve that issue I am also stuck in this issue

**Comment by ErAbhishekChandani** [comment]
This is already resolved, in previous release please check in 1.9.

**Comment by m4f1h4rd** [comment]
What about swift version?
