### ISSUE TITLE
Access to UITextField's _placeholderLabel ivar is prohibited

### ISSUE THREAD

**Issue by sadanand-lowanshi** [ErAbhishekChandani/ACFloatingTextfield#73]
iOS 13 Crashing due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'

we are getting crashes because of how the framework uses KVC to access Apple's private APIs.

**Comment by ErAbhishekChandani** [comment]
This is is resolved please make sure you are using latest version of pods.

Thanks

**Comment by SriSamVictor** [comment]
Am also got that the same issue "iOS 13 Crashing due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel Ivar is prohibited. This is an application bug'.

Once I update the latest version. It will be working fine. Thanks buddy.

**Comment by ErAbhishekChandani** [comment]
Thanks

**Comment by ErAbhishekChandani** [comment]
FIXED
